import js from "@eslint/js";
import globals from "globals";
import react from "eslint-plugin-react";
import reactHooks from "eslint-plugin-react-hooks";

/** @type {import("eslint").Linter.Config[]} */
export default [
	{
		ignores: [
			"**/node_modules/**",
			"frontend/build/**",
			"frontend/src/assets/**", // generated by @svgr/cli
			"**/*.min.js",
		],
	},

	js.configs.recommended,

	// Backend: CommonJS, Node globals.
	{
		files: ["backend/**/*.js"],
		languageOptions: {
			ecmaVersion: 2023,
			sourceType: "commonjs",
			globals: { ...globals.node },
		},
		rules: {
			"no-console": ["warn", { allow: ["error"] }],
			"no-unused-vars": [
				"error",
				{ argsIgnorePattern: "^_|^next$", caughtErrors: "none" },
			],
			eqeqeq: ["error", "smart"],
			"prefer-const": "error",
		},
	},

	// Operator-facing CLI scripts: printing to stdout is the point.
	{
		files: ["backend/scripts/**/*.js"],
		rules: { "no-console": "off" },
	},

	// Frontend: ES modules, browser globals, JSX.
	{
		files: ["frontend/**/*.{js,jsx}"],
		languageOptions: {
			ecmaVersion: 2023,
			sourceType: "module",
			globals: { ...globals.browser },
			parserOptions: { ecmaFeatures: { jsx: true } },
		},
		settings: { react: { version: "detect" } },
		plugins: { react, "react-hooks": reactHooks },
		rules: {
			...react.configs.flat.recommended.rules,
			...reactHooks.configs.recommended.rules,
			// The project uses the automatic JSX runtime, so React does not
			// need to be in scope.
			"react/react-in-jsx-scope": "off",
			"react/prop-types": "off",
			// Apostrophes and quotes in user-facing copy are fine.
			"react/no-unescaped-entities": "off",
			"no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
			eqeqeq: ["error", "smart"],
		},
	},

	// Config files run in Node even though they are ES modules.
	{
		files: ["*.config.{js,mjs}", "frontend/vite.config.js"],
		languageOptions: {
			sourceType: "module",
			globals: { ...globals.node },
		},
	},

	// Mongo initialisation scripts run inside mongosh, not Node.
	{
		files: ["ops/mongo-init/*.js"],
		languageOptions: {
			sourceType: "script",
			globals: {
				...globals.node,
				db: "writable",
				print: "readonly",
				rs: "readonly",
			},
		},
		rules: { "no-console": "off" },
	},
];
